name: Build VM Tool
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar MSVC (Entorno de Visual Studio)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compilar con GDI+ y Multimedia
        run: |
          cl.exe /EHsc /O2 /D_CRT_SECURE_NO_WARNINGS main.cpp /link /OUT:chaos_tool.exe
          
      - name: Guardar el ejecutable
        uses: actions/upload-artifact@v4
        with:
          name: program-exe
          path: virus.exe
